name: 'Hello world' 
description: 'Regarts someone and save actual date' 
inputs: 
  who-to-greet: # id of input 
    description: 'Who regarts' 
    required: true
    default: '....... friends' 
outputs: 
  time: # id of the output 
    description: 'The date that meet you' 
runs: 
  using: 'docker' 
  image: 'Dockerfile'
  args: 
    - ${{ inputs.who-togreet }}
